<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
	public function isOverbooking($date)
	{
		$nbTickets = 0;

		$queryBuilder = $this->createQueryBuilder('o');
		$queryBuilder->where('o.bookingDate = :bookingDate')->setParameter('bookingDate', $date);
		$orderList = $queryBuilder->getQuery()->getArrayResult();

		foreach($orderList as $order)
		{
			$nbTickets += $order['quantity'];
		}

		if($nbTickets >= 1000)
		{
			return true;
		}
		else
		{
			return false;
		}
	}

}
