<?php

namespace AppBundle\Repository;

/**
 * OrderTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
