app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_booking:
    path:      /booking
    defaults:
      _controller: AppBundle:Default:booking

app_info:
    path:      /info
    defaults:
      _controller: AppBundle:Default:info

app_summary:
    path:      /summary
    defaults:
      _controller: AppBundle:Default:summary